package: kganalytics
version: '1.7.1'
author: 'Kreatif'
debug: 0
compile: 0

requires:
    php:
        version: '>=7, <9'

page:
    title: Google Analytics
    block: system
    prio: 90
    icon: rex-icon fa-chart-pie
    perm: kganalytics[]
    subpages:
        settings:
            title: 'translate:settings'
            icon: rex-icon fa-sliders
            perm: kganalytics[settings]
        info:
            title: 'translate:info'
            icon: rex-icon fa-info
            itemclass: pull-right
            perm: kganalytics[settings]


pages:
    system/log/kga_events:
        title: KGA Events
        perm: admin[]
    system/log/kga_debug:
        title: KGA Debug Log
        perm: admin[]